# Generated by Django 4.0.3 on 2022-04-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=12, verbose_name='Número de telefone'),
            preserve_default=False,
        ),
    ]
