# Generated by Django 4.0.3 on 2022-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name='Número de telefone'),
        ),
    ]
